db_user = "root"
db_password = "akasis12"
dev_host = "localhost"
aws_prod_host = "mysql-blog-dbinstance.cbsvb1n2khfm.us-east-1.rds.amazonaws.com"
aws_prod_user = "ljheidrick"
aws_prod_password = "akasis12"
db_name = "blog"